baseURL = "https://codextypes.com/"
languageCode = "en-us"
title = "Josh Austin"
theme="hyde"

[params]
  description = "Java Software Engineer from Chicago. Follower of Jesus. Beliefs and opinions are my own."
  themeColor = "theme-base-0d"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/codextypes"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/codextypes"},
      {Name = "Twitter", URL = "https://twitter.com/codextypes"},
  ]

[markup.goldmark.renderer]
  unsafe= true